name: gam-bp
title: GAM
summary: GAM is a command line tool for Google Workspace admins.
description: |
   GAM is a command line tool that allows administrators to manage many aspects
   of their Google Workspace (formerly G Suite / Google Apps) Account.
version: "6.58"
confinement: strict
grade: stable
base: core22
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

apps:
  gam:
    command: bin/gam
    plugs:
      - network
      - network-bind
    environment:
      XDG_CONFIG_HOME: "$SNAP_USER_COMMON/.config/"

parts:
  gam:
    plugin: python
    source: https://github.com/GAM-team/GAM.git
    build-packages:
      - curl
      - libpcsclite-dev
      - swig
    override-pull: |
      craftctl default
      git checkout v6.58
      # remove cruft (src/LICENSE just symlinks to LICENSE)
      rm -rf src/.gitignore src/LICENSE
      # patch to use XDG config dirs
      git apply ../../patches/src/xdg.patch
      # move the actual files into the root
      mv src/* .
      # clean up
      rmdir src
      # this will be created later, but let's pre-populate it now
      mkdir -p $CRAFT_PART_INSTALL/lib/python3.10/site-packages/
      # retrieve roots.pem and stage it in site-packages
      curl -o roots.pem https://pki.goog/roots.pem
      mkdir -p $CRAFT_PART_INSTALL/lib/python3.10/site-packages/
      cp roots.pem $CRAFT_PART_INSTALL/lib/python3.10/site-packages/
      # create behavioural override files and stage them also
      touch noupdatecheck.txt noshorturls.txt
      cp noupdatecheck.txt noshorturls.txt $CRAFT_PART_INSTALL/lib/python3.10/site-packages/
    after: [patches]
  patches:
    source: patches
    plugin: dump
