name: gam-bp
title: GAM
summary: GAM is a command line tool for Google Workspace admins.
description: |
   GAM is a command line tool that allows administrators to manage many aspects
   of their Google Workspace (formerly G Suite / Google Apps) Account.
adopt-info: gam
confinement: strict
grade: stable
base: core24
platforms:
  amd64:
  arm64:

apps:
  gam:
    command: bin/gam
    plugs:
      - network
      - network-bind
    environment:
      GAMCFGDIR: "$SNAP_USER_COMMON/.config/"

parts:
  gam:
    plugin: python
    source: https://github.com/GAM-team/GAM.git
    build-packages:
      - curl
      - libpcsclite-dev
      - swig
    python-requirements: [src/requirements.txt]
    override-pull: |
      craftctl default
      # build the latest tagged release
      latest_tag=$(git tag --list | grep '^v' | tail -1)
      git checkout "${latest_tag?}"
      craftctl set version=$(echo "${latest_tag?}" | sed 's/^v//')
      # patch setup.cfg to work around missing gam.var definition
      sed -i "s/attr: gam.var.GAM_VERSION/${latest_tag?}/" src/setup.cfg
      # remove cruft (src/LICENSE just symlinks to LICENSE)
      rm -rf src/.gitignore src/LICENSE
      # work around case-sensitivity issue
      cd src
      [ -f README.md ] && ln -s README.md readme.md
      cd ..
      # this will be created later, but let's pre-populate it now
      mkdir -p "$CRAFT_PART_INSTALL"/lib/python3.12/site-packages/
      # retrieve roots.pem and stage it in site-packages
      curl -o "$CRAFT_PART_INSTALL"/lib/python3.12/site-packages/roots.pem https://pki.goog/roots.pem
      # create behavioural override files and stage them also
      touch "$CRAFT_PART_INSTALL"/lib/python3.12/site-packages/noupdatecheck.txt
      touch "$CRAFT_PART_INSTALL"/lib/python3.12/site-packages/noshorturls.txt
      # copy documentation file
      mkdir -p "$CRAFT_PART_INSTALL"/lib/python3.12/site-packages/gam
      cp -v src/GamCommands.txt "$CRAFT_PART_INSTALL"/lib/python3.12/site-packages/gam/
